apiVersion: batch/v1
kind: Job
metadata:
  name: training-job
  namespace: flyingthings-standalone
spec:
  selector: {}
  template:
    metadata:
      name: training
    spec:
      nodeSelector:
        nvidia.com/gpu.deploy.driver: 'true'  
      containers:
        - name: training
          image: image-registry.openshift-image-registry.svc:5000/flyingthings-standalone/training-job
          env:
          - name: MINIO_CLIENT_URL
            value: "http://util02.davenet.local"
          - name: BATCH_SIZE
            value: "2"
          - name: NUM_EPOCHS
            value: "3"
          command:
            - /opt/app-root/src/simplevis-data/run-training.sh
          volumeMounts:
            - mountPath: /opt/app-root/src/simplevis-data/workspace
              name: workspace
            - mountPath: /dev/shm
              name: dshm
          resources:
            limits:
              nvidia.com/gpu: 1
      volumes:
        - name: workspace
          emptyDir: {}
        - name: dshm
          emptyDir:
             medium: Memory
      restartPolicy: Never
