apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: minio-server-setup
spec:
  params:
    - default: 'https://github.com/redhat-na-ssa/flyingthings.git'
      description: url of the git repo for the code of deployment
      name: git-url
      type: string
    - default: develop
      description: revision to be used from repo of the code for deployment
      name: git-revision
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: run-minio-commands
      taskSpec:
        steps:
          - name: run-batch-file
            image: ubi9:latest
            script: |
              #!/usr/bin/env bash
              echo "Hello from Bash!" \
              && /workspace/output/source/minio-client/bucket-ops.sh
      runAfter:
        - fetch-repository
      workspaces:
        - name: output
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace