apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: image-resize
  namespace: flyingthings-standalone
spec:
  params:
    - name: SIMPLEVIS_DATA
      type: string
    - name: IMG_WIDTH
      type: string
    - name: IMG_HEIGHT
      type: string
  steps:
    - name: image-resize
      image: image-registry.openshift-image-registry.svc:5000/flyingthings-standalone/base-ubi9:latest
      script: |
        set -x \
        && cd $(params.SIMPLEVIS_DATA)/workspace/datasets \
        && mkdir images_original \
        && cp images/* images_original/ \
        && $(workspaces.source.path)/source/training/100-image-resize.py images $(params.IMG_WIDTH) $(params.IMG_HEIGHT)
      env:
        - name: SIMPLEVIS_DATA
          value: $(params.SIMPLEVIS_DATA)
        - name: BASEDIR
          value: $(workspaces.source.path)/source/training
  workspaces:
    - name: workspace
      mountPath: /opt/app-root/src/simplevis-data/workspace
    - name: source
      mountPath: /source
