apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'flyingthings-model-deployment'
spec:
  selector:
    matchLabels:
      app: flyingthings-model
  replicas: 1
  template:
    metadata:
      labels:
        app: flyingthings-model
    spec:
      containers:
        - name: container
          image: >-
            image-registry.openshift-image-registry.svc:5000/flyingthings-standalone/flyingthings-model:latest
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            # - mountPath: /opt/app-root/src/simplevis-data
            #   name: simplevis-data
            - mountPath: /opt/app-root/src
              name: workspace
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: workspace
        # - name: simplevis-data
        #   emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
---
apiVersion: v1
kind: Service
metadata:
  name: flyingthings-model-svc
spec:
  selector:
    app: flyingthings-model
  ports:
    - protocol: TCP
      port: 8000
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: flyingthings-model-rt
  labels: {}
spec:
  to:
    kind: Service
    name: flyingthings-model-svc
  tls: null
  path: /
  port:
    targetPort: 8000
