apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: training-pipeline
  namespace: flyingthings-standalone
spec:
  params: 
    - name: git-url
      default: https://github.com/redhat-na-ssa/flyingthings.git
      description: url of the git repo for the code of deployment
      type: string
    - name: git-revision
      default: develop
      description: revision to be used from repo of the code for deployment
      type: string
    - name: BATCH_SIZE
      type: string
    - name: NUM_EPOCHS
      type: string
    - name: WEIGHTS
      type: string
    - name: BASE_MODEL
      type: string
    - name: MODEL_CLASSES
      type: string
    - name: MINIO_ENDPOINT
      type: string
    - name: DATASET_ZIP
      type: string
    - name: SIMPLEVIS_DATA
      type: string
    - name: MINIO_BUCKET
      type: string
    - name: MINIO_ACCESSKEY
      type: string
    - name: MINIO_SECRETKEY
      type: string
    - name: MINIO_CLIENT_URL
      type: string
  tasks: 
    - name: fetch-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: train-a-model
      taskRef:
        name: training-model-task
      params:
        - name: BATCH_SIZE
          value: $(params.BATCH_SIZE)
        - name: NUM_EPOCHS
          value: $(params.NUM_EPOCHS)
        - name: WEIGHTS
          value: $(params.WEIGHTS)
        - name: BASE_MODEL
          value: $(params.BASE_MODEL)
        - name: MODEL_CLASSES
          value: $(params.MODEL_CLASSES)
        - name: MINIO_ENDPOINT
          value: $(params.MINIO_ENDPOINT)
        - name: DATASET_ZIP
          value: $(params.DATASET_ZIP)
        - name: SIMPLEVIS_DATA
          value: $(params.SIMPLEVIS_DATA)
        - name: MINIO_BUCKET
          value: $(params.MINIO_BUCKET)
        - name: MINIO_ACCESSKEY
          value: $(params.MINIO_ACCESSKEY)
        - name: MINIO_SECRETKEY
          value: $(params.MINIO_SECRETKEY)
        - name: MINIO_CLIENT_URL
          value: $(params.MINIO_CLIENT_URL)
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: training-model-task
  namespace: flyingthings-standalone
spec:
  params:
    - name: BATCH_SIZE
      type: string
    - name: NUM_EPOCHS
      type: string
    - name: WEIGHTS
      type: string
    - name: BASE_MODEL
      type: string
    - name: MODEL_CLASSES
      type: string
    - name: MINIO_ENDPOINT
      type: string
    - name: DATASET_ZIP
      type: string
    - name: SIMPLEVIS_DATA
      type: string
    - name: MINIO_BUCKET
      type: string
    - name: MINIO_ACCESSKEY
      type: string
    - name: MINIO_SECRETKEY
      type: string
    - name: MINIO_CLIENT_URL
      type: string
  steps:
    - image: image-registry.openshift-image-registry.svc:5000/flyingthings-standalone/training-job:latest
      # command: ["/opt/app-root/src/simplevis-data/run-training.sh"]
      script: |
        $(workspaces.source.path)/source/training-job/run-training.sh
      env:
        - name: BATCH_SIZE
          value: $(params.BATCH_SIZE)
        - name: NUM_EPOCHS
          value: $(params.NUM_EPOCHS)
        - name: WEIGHTS
          value: $(params.WEIGHTS)
        - name: BASE_MODEL
          value: $(params.BASE_MODEL)
        - name: MODEL_CLASSES
          value: $(params.MODEL_CLASSES)
        - name: MINIO_ENDPOINT
          value: $(params.MINIO_ENDPOINT)
        - name: DATASET_ZIP
          value: $(params.DATASET_ZIP)
        - name: SIMPLEVIS_DATA
          value: $(params.SIMPLEVIS_DATA)
        - name: BASEDIR
          value: $(workspaces.source.path)/source/training-job
        - name: MINIO_BUCKET
          value: $(params.MINIO_BUCKET)
        - name: MINIO_ACCESSKEY
          value: $(params.MINIO_ACCESSKEY)
        - name: MINIO_SECRETKEY
          value: $(params.MINIO_SECRETKEY)
        - name: MINIO_CLIENT_URL
          value: $(params.MINIO_CLIENT_URL)
      resources:
        limits:
          nvidia.com/gpu: 1
      volumeMounts:
        - name: workspace
          mountPath: /opt/app-root/src/simplevis-data/workspace
        - mountPath: /dev/shm
          name: dshm
  volumes:
    - name: workspace
      emptyDir: {}
    - name: dshm
      emptyDir:
          medium: Memory
  workspaces:
    - name: source
      mountPath: /source