apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-training-pipeline
spec:
  pipelineRef:
    name: training-pipeline
  params:
    - name: git-url
      value: https://github.com/redhat-na-ssa/flyingthings.git
    - name: git-revision
      value: develop
    - name: BATCH_SIZE
      value: "2"
    - name: NUM_EPOCHS
      value: "3"
    - name: WEIGHTS
      value: flyingthings.pt
    - name: BASE_MODEL
      value: yolov8n.pt
    - name: MODEL_CLASSES
      value: flyingthings.yaml
    - name: MINIO_ENDPOINT
      value: http://minio:9000
      # value: http://qnap-nas.davenet.local:49154
    - name: DATASET_ZIP
      value: flyingthings-yolo.zip
    - name: SIMPLEVIS_DATA
      value: /opt/app-root/src/simplevis-data
    - name: BASEDIR
      value: /opt/app-root/src
    - name: MINIO_BUCKET
      value: flyingthings
    - name: MINIO_ACCESSKEY
      value: minioadmin
    - name: MINIO_SECRETKEY
      value: minioadmin
    - name: MINIO_CLIENT_URL
      value: https://dl.min.io/client/mc/release/linux-amd64
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 500Mi
          volumeMode: Filesystem