apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: get-pretrained-model-run
  namespace: flyingthings-standalone
spec:
  params:
    - name: git-url
      value: 'https://github.com/redhat-na-ssa/flyingthings.git'
    - name: git-revision
      value: develop
    - name: BATCH_SIZE
      value: '-1'
    - name: NUM_EPOCHS
      value: '1'
    - name: WEIGHTS
      value: yolov8n.pt
    - name: MINIO_ENDPOINT
      value: 'http://minio:9000'
    - name: MINIO_BUCKET
      value: flyingthings
    - name: MINIO_ACCESSKEY
      value: minioadmin
    - name: MINIO_SECRETKEY
      value: minioadmin
    - name: MINIO_CLIENT_URL
      value: 'https://dl.min.io/client/mc/release/linux-amd64'
  pipelineRef:
    name: get-pretrained-model
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 500Mi