apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: run-training-pipeline
  namespace: flyingthings-standalone
spec:
  params:
    - name: IMAGE
      type: string
    - name: BATCH_SIZE
      type: string
    - name: NUM_EPOCHS
      type: string
    - name: WEIGHTS
      type: string
    - name: BASE_MODEL
      type: string
    - name: MODEL_CLASSES
      type: string
    - name: MINIO_ENDPOINT
      type: string
    - name: DATASET_ZIP
      type: string
    - name: SIMPLEVIS_DATA
      type: string
    - name: BASEDIR
      type: string
    - name: MINIO_BUCKET
      type: string
    - name: MINIO_ACCESSKEY
      type: string
    - name: MINIO_SECRETKEY
      type: string
    - name: MINIO_CLIENT_URL
      type: string

  workspaces:
    - name: workspace
  tasks:
    - name: run-container
      params: 
        - name: IMAGE
          value: "$(params.IMAGE)"
        - name: BATCH_SIZE
          value: $(params.BATCH_SIZE)
        - name: NUM_EPOCHS
          value: $(params.NUM_EPOCHS)
        - name: WEIGHTS
          value: $(params.WEIGHTS)
        - name: BASE_MODEL
          value: $(params.BASE_MODEL)
        - name: MODEL_CLASSES
          value: $(params.MODEL_CLASSES)
        - name: MINIO_ENDPOINT
          value: $(params.MINIO_ENDPOINT)
        - name: DATASET_ZIP
          value: $(params.DATASET_ZIP)
        - name: SIMPLEVIS_DATA
          value: $(params.SIMPLEVIS_DATA)
        - name: BASEDIR
          value: $(params.BASEDIR)
        - name: MINIO_BUCKET
          value: $(params.MINIO_BUCKET)
        - name: MINIO_ACCESSKEY
          value: $(params.MINIO_ACCESSKEY)
        - name: MINIO_SECRETKEY
          value: $(params.MINIO_SECRETKEY)
        - name: MINIO_CLIENT_URL
          value: $(params.MINIO_CLIENT_URL)
      taskSpec:
        params:
          - name: IMAGE
          - name: BATCH_SIZE
          - name: NUM_EPOCHS
          - name: WEIGHTS
          - name: BASE_MODEL
          - name: MODEL_CLASSES
          - name: MINIO_ENDPOINT
          - name: DATASET_ZIP
          - name: SIMPLEVIS_DATA
          - name: BASEDIR
          - name: MINIO_BUCKET
          - name: MINIO_ACCESSKEY
          - name: MINIO_SECRETKEY
          - name: MINIO_CLIENT_URL
        steps:
          - name: run-container-step
            image: $(params.IMAGE)
            resources:
              limits:
                nvidia.com/gpu: 1
            env:
              - name: BATCH_SIZE
                value: $(params.BATCH_SIZE)
              - name: NUM_EPOCHS
                value: $(params.NUM_EPOCHS)
              - name: WEIGHTS
                value: $(params.WEIGHTS)
              - name: BASE_MODEL
                value: $(params.BASE_MODEL)
              - name: MODEL_CLASSES
                value: $(params.MODEL_CLASSES)
              - name: MINIO_ENDPOINT
                value: $(params.MINIO_ENDPOINT)
              - name: DATASET_ZIP
                value: $(params.DATASET_ZIP)
              - name: SIMPLEVIS_DATA
                value: $(params.SIMPLEVIS_DATA)
              - name: BASEDIR
                value: $(params.BASEDIR)
              - name: MINIO_BUCKET
                value: $(params.MINIO_BUCKET)
              - name: MINIO_ACCESSKEY
                value: $(params.MINIO_ACCESSKEY)
              - name: MINIO_SECRETKEY
                value: $(params.MINIO_SECRETKEY)
              - name: MINIO_CLIENT_URL
                value: $(params.MINIO_CLIENT_URL)
            command:
              - "/bin/bash"
              - "-c"
              - |
                ls -l $(params.SIMPLEVIS_DATA) && $(params.SIMPLEVIS_DATA)/run-training.sh
      workspaces: []