apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'coco-model'
spec:
  selector:
    matchLabels:
      app: coco-model
  replicas: 1
  template:
    metadata:
      labels:
        app: coco-model
    spec:
      containers:
        - name: container
          image: >-
            image-registry.openshift-image-registry.svc:5000/flyingthings-standalone/model-server:latest
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: WEIGHTS
              value: model_pretrained.pt
            - name: BUILD_VER
              value: "0.0"
            - name: MODEL_CLASSES
              value: flyingthings.yaml
            - name: MINIO_ENDPOINT
              value: http://minio:9000
            - name: SIMPLEVIS_DATA
              value: /opt/app-root/src/simplevis-data
          volumeMounts:
            - mountPath: /opt/app-root/src/simplevis-data
              name: simplevis-data
      volumes:
        - name: simplevis-data
          emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
---
apiVersion: v1
kind: Service
metadata:
  name: coco-model-svc
spec:
  selector:
    app: coco-model
  ports:
    - protocol: TCP
      port: 8000
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: coco-model-rt
  labels: {}
spec:
  to:
    kind: Service
    name: coco-model-svc
  tls: null
  path: /
  port:
    targetPort: 8000
